spring:
  application:
    name: forum-backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    enabled: false

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8090

logging:
  level:
    org.springframework.com: DEBUG
    com.january0001.project.forumbackend: DEBUG